-- S3: a total order on the messages of a conversation.
--
-- The context window is the last N messages "in order" (ADR-023), and until now
-- the only ordering available was created_at. That is a JS Date, so it is
-- millisecond precision: a user message and the answer to it, written in the
-- same millisecond, have no defined order at all. It is not hypothetical — a
-- turn against a stubbed provider closes well inside a millisecond, and the
-- follow-up would then be sent the two halves of a conversation in whichever
-- order the planner happened to pick.
--
-- A monotonic column decides it. This is insert order, which for a Message is
-- creation order: a Message is written once, when the turn closes (ADR-013),
-- and never updated, so the two cannot diverge.
--
-- Purely a persistence concern. The mapper neither reads nor writes seq and the
-- domain has no idea it exists.

ALTER TABLE "messages" ADD COLUMN IF NOT EXISTS "seq" bigint;

-- Backfilled explicitly rather than left to the order Postgres happens to
-- rewrite rows in. created_at is all these rows have; ties break on id so the
-- result is the same whenever this runs.
UPDATE "messages" AS m
SET "seq" = numbered.rank
FROM (
  SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS rank
  FROM "messages"
) AS numbered
WHERE m."id" = numbered."id" AND m."seq" IS NULL;

ALTER TABLE "messages" ALTER COLUMN "seq" SET NOT NULL;
ALTER TABLE "messages" ALTER COLUMN "seq" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Start the sequence past the backfilled rows, so the next insert does not
-- collide with one of them.
SELECT setval(
  pg_get_serial_sequence('messages', 'seq'),
  COALESCE((SELECT MAX("seq") FROM "messages"), 0) + 1,
  false
);

CREATE UNIQUE INDEX IF NOT EXISTS "messages_conversation_seq_idx"
  ON "messages" ("conversation_id", "seq");
